name: coverage

"on":
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install development environment
        run: scripts/develop
      - name: Run coverage
        run: scripts/coverage --html
      - name: Upload HTML coverage
        uses: actions/upload-artifact@v4
        with:
          name: htmlcov
          path: htmlcov/
