name: lint

"on":
  pull_request:
  push:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install development environment
        run: scripts/develop
      - name: Check formatting
        run: scripts/format --check --diff
      - name: Run lint
        run: scripts/lint
